#!/usr/bin/env bash
# =============================================================================
#  Backup cron.     scripts/cron.sh install|uninstall|status|show
# -----------------------------------------------------------------------------
#  The SCHEDULES live in .env, not in this script and not in a crontab someone
#  edited on the server two years ago. `install` renders them into the invoking
#  user's crontab between managed markers; `uninstall` removes exactly that
#  block and nothing else; `show` prints what would be installed.
#
#  It is the USER's crontab, not /etc/cron.d, so no root is needed and the jobs
#  run as the account that owns the checkout — the same account that can talk
#  to the docker socket. A root cron running `docker compose` in a user's
#  checkout works right up until it writes a root-owned file into backups/.
#
#  `status` answers the only question worth asking about a backup cron: not
#  "is it installed" but "when did each job last actually succeed". A cron that
#  is installed and failing every night looks identical to a working one from
#  every angle except this.
# =============================================================================
set -euo pipefail

# shellcheck source=scripts/lib.sh
source "$(dirname "$0")/lib.sh"

assert_configured

ACTION="${1:-status}"
STACK="$(cfg STACK_NAME otc)"
BEGIN="# >>> ${STACK}-docker-control >>>"
END="# <<< ${STACK}-docker-control <<<"
CRON_LOG="$(abs "$(cfg BACKUP_DIR ./backups)")/cron.log"

# Each row: env key | what it runs | label
jobs=(
    "BACKUP_CRON_DB|scripts/backup.sh db --no-retention|backup db"
    "BACKUP_CRON_REDIS|scripts/backup.sh redis --no-retention|backup redis"
    "BACKUP_CRON_FILES|scripts/backup.sh files --no-retention|backup files"
    "BACKUP_CRON_CONFIG|scripts/backup.sh config --no-retention|backup config"
    "BACKUP_CRON_RETENTION|scripts/retention.sh|retention"
    "BACKUP_CRON_SYNC|scripts/sync.sh|off-site sync"
    "DISK_GUARD_CRON|scripts/disk-guard.sh --enforce|disk guard"
)

render() {
    printf '%s\n' "$BEGIN"
    printf '# Generated by scripts/cron.sh from .env on %s. Do not edit by hand:\n' "$(iso)"
    printf '# change the BACKUP_CRON_* values in %s and re-run `make cron-install`.\n' "$ENV_FILE"
    printf 'SHELL=/bin/bash\n'
    # cron's default PATH is /usr/bin:/bin, which does not include
    # /usr/local/bin — where docker compose plugins and zstd often live. A
    # backup that works by hand and fails on cron is nearly always this.
    printf 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n'
    printf 'CRON_TZ=%s\n' "$(cfg TZ Asia/Dhaka)"
    printf 'TZ=%s\n' "$(cfg TZ Asia/Dhaka)"
    # Empty MAILTO silences cron's own mail. Notification goes through
    # BACKUP_NOTIFY_CMD, which reaches somewhere people actually look.
    printf 'MAILTO=""\n'

    local key cmd label sched
    for row in "${jobs[@]}"; do
        IFS='|' read -r key cmd label <<<"$row"
        sched="$(cfg "$key")"
        [ -n "$sched" ] || { printf '# %-22s disabled (%s is empty)\n' "$label" "$key"; continue; }
        printf '%s cd %s && %s >> %s 2>&1\n' \
            "$sched" "$REPO_ROOT" "$REPO_ROOT/$cmd" "$CRON_LOG"
    done
    printf '%s\n' "$END"
}

# Last line of the operations log matching a job, with its status. This is
# what turns "installed" into "working".
last_run() {
    local pattern="$1"
    [ -f "$LOG_FILE" ] || return 0
    # `|| true` because grep exits 1 when a target has never run, and under
    # `set -o pipefail` that failure propagates out of the command
    # substitution and kills the script mid-table — so `make cron-status`
    # printed the first few rows and exited 1, which reads like a real fault.
    grep -F "$pattern" "$LOG_FILE" 2>/dev/null | tail -n1 || true
}

case "$ACTION" in

show)
    render
    ;;

install)
    need crontab "cron is not installed. On Debian/Ubuntu: sudo apt install cron"

    # A laptop that sleeps through 02:00 runs no backups and reports nothing.
    # Refusing here is the difference between "we have nightly backups" being
    # true and being believed.
    if [ "$(cfg DEPLOY_ENV)" != "production" ] && [ "${FORCE:-0}" != 1 ]; then
        die "DEPLOY_ENV=$(cfg DEPLOY_ENV), not production." \
            "A machine that sleeps runs no backups and says nothing about it." \
            "If you mean it:  FORCE=1 make cron-install"
    fi

    # Validate every schedule before touching the live crontab. `crontab file`
    # rejects the whole file on one bad line, and the error message names a
    # line number in a temporary file that no longer exists.
    for row in "${jobs[@]}"; do
        IFS='|' read -r key _ label <<<"$row"
        sched="$(cfg "$key")"
        [ -n "$sched" ] || continue
        fields="$(awk '{print NF}' <<<"$sched")"
        [ "$fields" = 5 ] || die "$key has $fields fields, not 5: '$sched'" \
            "Five fields:  minute hour day-of-month month day-of-week" \
            "  0 2 * * *      02:00 every day" \
            "  40 2 * * 0     02:40 on Sundays"
    done

    tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
    crontab -l 2>/dev/null | sed "\\|^${BEGIN}\$|,\\|^${END}\$|d" > "$tmp" || true
    render >> "$tmp"
    crontab "$tmp"

    c_ok "installed into the crontab of $(whoami)"
    render | grep -E '^[0-9*]' | sed 's/^/    /'

    # Honesty about timezones: CRON_TZ is honoured by cronie and by recent
    # Debian cron, and ignored by some others, in which case these run in the
    # system timezone. Print both so the difference is visible now rather than
    # during an incident.
    sys_tz="$(timedatectl show -p Timezone --value 2>/dev/null || cat /etc/timezone 2>/dev/null || echo unknown)"
    if [ "$sys_tz" != "$(cfg TZ)" ]; then
        c_warn "CRON_TZ=$(cfg TZ) but the system timezone is $sys_tz"
        c_info "if this cron ignores CRON_TZ, the jobs run on $sys_tz"
    fi
    c_info "output goes to $CRON_LOG"
    [ -n "$(cfg BACKUP_NOTIFY_CMD)" ] || \
        c_warn "BACKUP_NOTIFY_CMD is unset — a failing backup will be silent"
    ;;

uninstall)
    need crontab
    crontab -l 2>/dev/null | grep -qF "$BEGIN" || { c_ok "nothing installed"; exit 0; }
    tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
    crontab -l 2>/dev/null | sed "\\|^${BEGIN}\$|,\\|^${END}\$|d" > "$tmp"
    crontab "$tmp"
    c_ok "removed the ${STACK} block from the crontab of $(whoami)"
    c_warn "nothing is scheduled now — no backups will be taken"
    ;;

status)
    c_head "Scheduled"
    if crontab -l 2>/dev/null | grep -qF "$BEGIN"; then
        crontab -l 2>/dev/null | sed -n "\\|^${BEGIN}\$|,\\|^${END}\$|p" \
            | grep -E '^[0-9*]' | sed 's/^/  /'
    else
        c_warn "no cron block installed:  make cron-install"
    fi

    c_head "Last outcome"
    # The number that matters. An installed schedule proves nothing.
    now="$(date +%s)"
    for probe in "backup db|db" "backup redis|redis" "backup files|files" \
                 "backup config|config" "retention|retention" "disk-guard|disk guard"
    do
        IFS='|' read -r pattern label <<<"$probe"
        line="$(last_run "$pattern")"
        if [ -z "$line" ]; then
            printf '  %-14s %snever run%s\n' "$label" "$C_YLW" "$C_OFF"
            continue
        fi
        when="$(cut -f1 <<<"$line")"
        status="$(cut -f2 <<<"$line")"
        age=$(( (now - $(date -d "$when" +%s 2>/dev/null || echo "$now")) / 3600 ))
        # An `a && b && c=x` chain as the LAST command of a loop body under
        # `set -e` terminates the script whenever a is false — here, on the
        # first FAIL row, so the status table silently stopped halfway and
        # `make cron-status` exited 1. Written as an if, it cannot.
        colour="$C_GRN"
        if [ "$status" != OK ]; then
            colour="$C_RED"
        elif [ "$age" -gt 48 ]; then
            # Last succeeded 48h ago on a daily schedule is a broken backup,
            # whatever that last line says.
            colour="$C_YLW"
        fi
        printf '  %-14s %s%-4s%s  %s  (%dh ago)\n' \
            "$label" "$colour" "$status" "$C_OFF" "$when" "$age"
    done

    c_head "Artifacts"
    "$REPO_ROOT/scripts/disk-guard.sh" --report 2>/dev/null | sed -n '/backups/p' | sed 's/^/  /'
    ;;

*)
    die "unknown action '$ACTION'." "Use: install | uninstall | status | show"
    ;;
esac
